# Generated by Django 5.1.1 on 2024-10-05 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPractitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=10)),
                ('license_class', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('RR', 'Review Ready'), ('DR', 'Draft'), ('RE', 'Reviewed')], max_length=2)),
                ('medical_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps_application.medicalpractitioner')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mps_application.resident')),
            ],
        ),
    ]
