# Generated by Django 5.1.1 on 2024-10-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpractitioner',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='medicalpractitioner',
            name='postal_code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='resident',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resident',
            name='postal_code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
