# Generated by Django 5.1.1 on 2024-10-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_application', '0002_medicalpractitioner_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='license_class',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='license_number',
        ),
        migrations.AddField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('NEW', 'New'), ('RENEW', 'Renewal')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='current_license',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='disability',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='doctor_certificate',
            field=models.CharField(choices=[('Fit', 'Fit'), ('Unfit', 'Unfit')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='epilepsy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='epilepsy_date_onset',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='epilepsy_last_seizure',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='expiry_date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='held_license',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='license_class',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='license_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='medical_condition',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='medical_review',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='othername',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='patient_months',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='patient_years',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='period',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='permit_type',
            field=models.CharField(choices=[('INDI', 'Individual'), ('TEMP', 'Temporary')], default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='reasons',
            field=models.CharField(choices=[('LOST', 'Lost'), ('STOL', 'Stolen'), ('DMAG', 'Damaged'), ('DFAC', 'Defaced'), ('CONF', 'Confiscated'), ('CHDE', 'Changed Details'), ('NORE', 'Non Receipt of Permit')], default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='temp_condition',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
