# Generated by Django 5.1.1 on 2024-10-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_application', '0003_remove_resident_license_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(choices=[('NEW', 'New'), ('RENEW', 'Renewal'), ('REPLA', 'Replacement')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_license',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='disability',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='doctor_certificate',
            field=models.CharField(choices=[('Fit', 'Fit'), ('Unfit', 'Unfit')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='epilepsy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='epilepsy_date_onset',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='epilepsy_last_seizure',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='held_license',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='license_class',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='license_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='medical_condition',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='medical_review',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='application',
            name='othername',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='patient_months',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='patient_years',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='application',
            name='period',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='permit_type',
            field=models.CharField(choices=[('INDI', 'Individual'), ('TEMP', 'Temporary')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='application',
            name='reasons',
            field=models.CharField(choices=[('LOST', 'Lost'), ('STOL', 'Stolen'), ('DMAG', 'Damaged'), ('DFAC', 'Defaced'), ('CONF', 'Confiscated'), ('CHDE', 'Changed Details'), ('NORE', 'Non Receipt of Permit')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('RR', 'Review Ready'), ('DR', 'Draft'), ('RE', 'Reviewed')], default='RR', max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='temp_condition',
            field=models.CharField(default='', max_length=10),
        ),
    ]
