# Generated by Django 5.1.1 on 2024-10-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_application', '0004_alter_application_application_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='medical_practitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mps_application.medicalpractitioner'),
        ),
    ]
