# Generated by Django 5.1.1 on 2024-10-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_application', '0005_alter_application_medical_practitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sectionTwo',
            field=models.CharField(choices=[('SUBMIT', 'Submitted'), ('NOSUB', 'Not submitted')], default='NOSUB', max_length=6),
        ),
    ]
