# Generated by Django 5.1.1 on 2024-10-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mps_application', '0006_application_sectiontwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='medical_condition',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3, null=True),
        ),
    ]
